import test from 'node:test';import assert from 'node:assert/strict';import {validateRating,craftScore,fitTaste,aspectIds} from '../model.mjs';
const rating=(i=0)=>({id:String(i),movieId:'film'+i,createdAt:new Date(2026,0,i+1).toISOString(),watchedOn:'2026-10-03',overall:3.5,spoilers:false,answers:aspectIds.map(id=>({aspectId:id,score:3,skipReason:null,note:''}))});
test('rubric mean and skip exclusion',()=>{const r=rating();assert.equal(craftScore(r.answers),3.75);r.answers[0].score=null;assert.equal(craftScore(r.answers),3.75);r.answers.forEach(a=>a.score=null);assert.equal(craftScore(r.answers),null)});
test('validation accepts zero scores and complete valid payload',()=>{const r=rating();r.answers[0].score=0;assert.equal(validateRating(r,new Set([r.movieId])),r)});
test('validation rejects invalid score, duplicates, ambiguous skip, malformed date and fewer than four scored aspects',()=>{for(const change of [r=>r.overall=3.7,r=>r.answers[0].score=5,r=>r.answers[0].aspectId='sound',r=>r.answers[0].score=null,r=>r.watchedOn='2026-02-30',r=>r.answers.forEach(a=>{a.score=null;a.skipReason='unsure'})]){let r=rating();change(r);assert.throws(()=>validateRating(r,new Set([r.movieId])))}});
test('cold start never claims weights',()=>assert.equal(fitTaste([rating()]).ready,false));
test('rewatches do not inflate training history',()=>{const rows=Array.from({length:20},(_,i)=>({...rating(i),movieId:'same'}));assert.equal(fitTaste(rows).n,1)});
test('identical overall ratings cannot infer a preference',()=>{const t=fitTaste(Array.from({length:12},(_,i)=>rating(i)));assert.equal(t.ready,false);assert.match(t.reason,/varied/)});
test('synthetic varied data can recover visual association without impact leakage',()=>{let seed=421;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return Math.floor(seed/4294967296*5)};const rows=Array.from({length:80},(_,i)=>{const r=rating(i);const x=random();r.overall=0.5+x;r.answers.forEach((a,j)=>a.score=j===3?x:random());return r});const t=fitTaste(rows);assert.equal(t.ready,true);assert.ok(t.weights.find(w=>w.id==='visuals').weight>0.5);assert.equal(t.weights.some(w=>w.id==='impact'),false);assert.ok(t.weights.every(w=>Number.isFinite(w.weight)&&w.weight>=0));assert.ok(Math.abs(t.weights.reduce((s,w)=>s+w.weight,0)-1)<1e-8)});
