import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import fs from 'node:fs/promises';
import {base,pool,fixture,cleanup} from './helpers/social-fixtures.mjs';
const people=[],movies=[],prefix='reco-'+randomUUID();let a,b;
const answers=['story','characters','performance','visuals','sound','editing','ideas','impact'].map(aspectId=>({aspectId,score:3,skipReason:null,note:'PRIVATE RECOMMENDER SENTINEL'}));
async function log(person,movieId,overall){return person.call('/api/ratings','POST',{movieId,overall,entryId:randomUUID(),watchedOn:'2026-10-06',spoilers:false,answers});}
const ids=data=>data.hybridRecommendations.map(r=>r.movieId);
test.before(async()=>{await fetch(base+'/api/health');a=await fixture('Recommendation Alex');b=await fixture('Recommendation Blair');people.push(a,b);for(let i=0;i<44;i++){const id=prefix+'-'+i;movies.push(id);await pool.query('INSERT INTO movies(id,title,year,genres,tags,rating_count,rating_mean) VALUES($1,$2,2020,$3,$4,40,4.9)',[id,'Fixture film '+i,JSON.stringify([i<28?'Drama':'Comedy']),JSON.stringify([prefix])]);}});
test('every new log changes inputs immediately, excludes watched films and remains stable between reads',async()=>{assert.equal((await log(a,movies[0],5)).status,201);const before=(await a.call('/api/taste')).data;assert.equal(before.algorithm.version,4);assert.equal(before.hybridRecommendations.length,8);assert.equal(before.hybridRecommendations.some(r=>r.movieId===movies[0]),false);assert.deepEqual(ids((await a.call('/api/taste')).data),ids(before));assert.equal((await log(a,movies[28],5)).status,201);const after=(await a.call('/api/taste')).data;assert.notDeepEqual(ids(after),ids(before));assert.ok(after.hybridRecommendations.some(r=>r.sourceMovieId===movies[28]));assert.equal(after.hybridRecommendations.some(r=>[movies[0],movies[28]].includes(r.movieId)),false);assert.equal(JSON.stringify(after).includes('PRIVATE RECOMMENDER SENTINEL'),false);assert.equal(after.ready,false);assert.deepEqual(ids((await a.call('/api/taste')).data),ids(after));});
test('explicit refresh serves relevant alternatives; reloads do not rotate or increment the shelf',async()=>{const before=(await a.call('/api/taste')).data;const fresh=await a.call('/api/recommendations/refresh','POST',{});assert.equal(fresh.status,200);assert.equal(ids(fresh.data).length,8);assert.ok(ids(fresh.data).filter(id=>ids(before).includes(id)).length<=2);const row=(await pool.query('SELECT refresh_revision FROM recommendation_shelves WHERE profile_id=$1',[a.profileId])).rows[0];assert.deepEqual(ids((await a.call('/api/taste')).data),ids(fresh.data));assert.equal((await pool.query('SELECT refresh_revision FROM recommendation_shelves WHERE profile_id=$1',[a.profileId])).rows[0].refresh_revision,row.refresh_revision);assert.equal((await a.call('/api/recommendations/refresh','POST',{profileId:b.profileId})).status,400);assert.equal((await a.call('/api/recommendations/refresh','POST',{} ,{'X-CSRF-Token':'forged'})).status,403);});
test('dismissal is persistent, private, reversible and separate from watchlist/rating signals',async()=>{const first=ids((await a.call('/api/taste')).data)[0];const dismissed=await a.call('/api/recommendations/feedback','POST',{movieId:first,dismissed:true});assert.equal(dismissed.status,200);assert.equal(ids(dismissed.data).includes(first),false);assert.equal(ids((await a.call('/api/taste')).data).includes(first),false);assert.equal((await a.call('/api/recommendations/hidden')).data.movies[0].id,first);assert.equal((await b.call('/api/recommendations/hidden')).data.movies.length,0);assert.equal((await a.call('/api/state')).data.ratings.length,2);assert.equal((await a.call('/api/state')).data.watchlist.includes(first),false);assert.equal((await a.call('/api/recommendations/feedback','POST',{movieId:first,dismissed:false})).status,200);assert.equal((await a.call('/api/recommendations/hidden')).data.movies.length,0);assert.equal((await a.call('/api/recommendations/feedback','POST',{movieId:first,dismissed:true,profileId:b.profileId})).status,400);assert.equal((await a.call('/api/recommendations/feedback','POST',{movieId:'nonexistent',dismissed:true})).status,404);assert.equal((await a.call('/api/recommendations/hidden?offset=-1')).status,400);});
test('saving a pick excludes it from the shelf and invalidates the database-backed input revision',async()=>{const first=ids((await a.call('/api/taste')).data)[0];const before=(await pool.query('SELECT input_revision FROM recommendation_shelves WHERE profile_id=$1',[a.profileId])).rows[0].input_revision;assert.equal((await a.call('/api/watchlist','POST',{movieId:first,saved:true})).status,200);assert.equal(ids((await a.call('/api/taste')).data).includes(first),false);assert.ok((await pool.query('SELECT input_revision FROM recommendation_shelves WHERE profile_id=$1',[a.profileId])).rows[0].input_revision>before);assert.equal((await a.call('/api/watchlist','POST',{movieId:first,saved:false})).status,200);});
test('editing a rating updates the journal key and deletion never returns the deleted profile data',async()=>{const before=(await pool.query('SELECT journal_key FROM recommendation_shelves WHERE profile_id=$1',[a.profileId])).rows[0].journal_key;assert.equal((await log(a,movies[28],1)).status,200);await a.call('/api/taste');assert.notEqual((await pool.query('SELECT journal_key FROM recommendation_shelves WHERE profile_id=$1',[a.profileId])).rows[0].journal_key,before);const ratings=(await a.call('/api/state')).data.ratings;for(const r of ratings)assert.equal((await a.call('/api/ratings/'+r.id,'DELETE')).status,200);assert.deepEqual(ids((await a.call('/api/taste')).data),[]);await pool.query(await fs.readFile(new URL('../db/recommendation-schema.sql',import.meta.url),'utf8'));assert.equal((await b.call('/api/recommendations/hidden')).status,200);});
test.after(async()=>{try{await cleanup(people);await pool.query('DELETE FROM movies WHERE id=ANY($1::text[])',[movies]);}finally{await pool.end();}});
