import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import vm from 'node:vm';import {fileURLToPath} from 'node:url';import {randomUUID,randomBytes,createHash} from 'node:crypto';import pg from 'pg';import {validateRating,craftScore,fitTaste,latestDistinct,modelAspectIds} from './model.mjs';import {importCatalogue} from './catalogue/import.mjs';import {buildFilmIndex,earlyRecommendations} from './public/recommend.js';
const root=path.dirname(fileURLToPath(import.meta.url));const isProd=process.env.NODE_ENV==='production';
if(!process.env.DATABASE_URL)throw Error('DATABASE_URL is required. Use npm run dev for a local real PostgreSQL instance.');
const sslConfig=process.env.PGSSL==='true'?{rejectUnauthorized:true}:(process.env.DATABASE_URL.includes('sslmode=')||(isProd&&!process.env.DATABASE_URL.includes('localhost')))?{rejectUnauthorized:false}:undefined;
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,max:10,ssl:sslConfig});
await pool.query(await fs.readFile(path.join(root,'db/schema.sql'),'utf8'));
const context={window:{}};vm.createContext(context);vm.runInContext(await fs.readFile(path.join(root,'public/data.js'),'utf8'),context);const {MOVIES,ASPECTS}=context.window;
for(const m of MOVIES)await pool.query('INSERT INTO movies(id,title,year,director,genres,runtime,poster,wallpaper) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET wallpaper=excluded.wallpaper,poster=excluded.poster',[m.id,m.title,m.year,m.director,JSON.stringify(m.genres),m.runtime,m.poster,m.wallpaper||'']);
for(const a of ASPECTS)await pool.query('INSERT INTO question_versions(version,aspect_id,label,prompt) VALUES(1,$1,$2,$3) ON CONFLICT DO NOTHING',[a.id,a.name,a.question]);
const catalogueMeta=await importCatalogue(pool,root);
const movieSelect=`SELECT id,title,year,director,genres,runtime,poster,wallpaper,original_title AS "originalTitle",movielens_id AS "movielensId",imdb_id AS "imdbId",tmdb_id AS "tmdbId",tags,rating_count AS "ratingCount",rating_mean::float8 AS "ratingMean",source FROM movies`;
const hash=s=>createHash('sha256').update(s).digest('hex');
function send(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj));}
async function body(req){let s='';for await(const chunk of req){s+=chunk;if(s.length>32000)throw Object.assign(Error('Request too large.'),{status:413});}try{return JSON.parse(s);}catch{throw Error('Invalid JSON.');}}
async function profile(req,res){const raw=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('af_session='))?.slice(11);if(raw&&/^[a-f0-9]{64}$/.test(raw)){const r=await pool.query('SELECT profile_id FROM sessions WHERE token_hash=$1 AND expires_at>now()',[hash(raw)]);if(r.rowCount)return r.rows[0].profile_id;}
 const id=randomUUID(),token=randomBytes(32).toString('hex');const client=await pool.connect();try{await client.query('BEGIN');await client.query('INSERT INTO profiles(id) VALUES($1)',[id]);await client.query("INSERT INTO sessions(token_hash,profile_id,expires_at) VALUES($1,$2,now()+interval '365 days')",[hash(token),id]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
 res.setHeader('Set-Cookie',`af_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=31536000${isProd?'; Secure':''}`);return id;}
async function getRatings(id){const r=await pool.query(`SELECT r.id,r.movie_id AS "movieId",r.overall::float8,r.watched_on::text AS "watchedOn",r.spoilers,r.created_at AS "createdAt",r.question_version AS "questionVersion",json_agg(json_build_object('aspectId',a.aspect_id,'score',a.score,'skipReason',a.skip_reason,'note',a.note) ORDER BY a.aspect_id) AS answers FROM ratings r JOIN answers a ON a.rating_id=r.id WHERE r.profile_id=$1 GROUP BY r.id ORDER BY r.created_at DESC`,[id]);return r.rows.map(r=>({...r,createdAt:r.createdAt.toISOString(),craft:craftScore(r.answers)}));}
const limiter=new Map();
export async function handleRequest(req,res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data:; style-src 'self'; style-src-attr 'unsafe-inline'; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
 try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){
  if(!['GET','POST','DELETE','PATCH'].includes(req.method))return send(res,405,{error:'Method not allowed.'});
  if(req.method!=='GET') {const origin=req.headers.origin;const proto=req.headers['x-forwarded-proto']||'http';const host=req.headers.host;const expected=process.env.APP_ORIGIN||(process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:`${proto}://${host}`);if(isProd&&!process.env.APP_ORIGIN&&!process.env.VERCEL_URL)return send(res,503,{error:'Set APP_ORIGIN before deploying.'});if(origin&&origin!==expected&&origin!==`https://${host}`&&origin!==`http://${host}`)return send(res,403,{error:'Cross-origin request blocked.'});if(req.headers['sec-fetch-site']==='cross-site')return send(res,403,{error:'Cross-site request blocked.'});if(req.method!=='DELETE'&&!req.headers['content-type']?.startsWith('application/json'))return send(res,415,{error:'Send application/json.'});}
  if(url.pathname==='/api/health'){await pool.query('SELECT 1');return send(res,200,{status:'ok',storage:'postgresql'});}
  const id=await profile(req,res);if(req.method!=='GET'){const now=Date.now();const entry=limiter.get(id)||{t:now,n:0};if(now-entry.t>60000){entry.t=now;entry.n=0;}entry.n++;limiter.set(id,entry);if(entry.n>60)return send(res,429,{error:'Please wait a moment before trying again.'});}
  if(req.method==='GET'&&url.pathname==='/api/state'){const [movies,ratings,watchlist,p]=await Promise.all([pool.query(movieSelect+' ORDER BY rating_count DESC,title'),getRatings(id),pool.query('SELECT movie_id FROM watchlist WHERE profile_id=$1',[id]),pool.query('SELECT contribute FROM profiles WHERE id=$1',[id])]);return send(res,200,{storage:'postgresql',profileKey:id,movies:movies.rows,ratings,catalogue:catalogueMeta,watchlist:watchlist.rows.map(r=>r.movie_id),contribute:p.rows[0].contribute});}
  if(req.method==='GET'&&url.pathname==='/api/movies'){const q=(url.searchParams.get('q')||'').slice(0,200);const genre=(url.searchParams.get('genre')||'').slice(0,80);const limit=Math.min(60,Math.max(1,Math.floor(Number(url.searchParams.get('limit')))||24));const offset=Math.max(0,Math.min(100000,Math.floor(Number(url.searchParams.get('offset')))||0));const pattern='%'+q.replace(/[\\%_]/g,'\\$&')+'%';const conditions=` WHERE ($1='%%' OR title ILIKE $1 OR original_title ILIKE $1 OR director ILIKE $1 OR year::text ILIKE $1) AND ($2='' OR genres ? $2)`;const count=await pool.query('SELECT count(*)::integer AS total FROM movies'+conditions,[pattern,genre]);const found=await pool.query(movieSelect+conditions+' ORDER BY rating_count DESC,title LIMIT $3 OFFSET $4',[pattern,genre,limit,offset]);return send(res,200,{movies:found.rows,total:count.rows[0].total,limit,offset});}
  if(req.method==='POST'&&url.pathname==='/api/ratings'){const b=await body(req);const films=await pool.query('SELECT id FROM movies WHERE id=$1',[b.movieId]);validateRating(b,new Set(films.rows.map(r=>r.id)));if(b.entryId&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(b.entryId))throw Error('Invalid entry ID.');const rid=b.entryId||randomUUID();const existing=await pool.query('SELECT profile_id FROM ratings WHERE id=$1',[rid]);if(existing.rowCount){if(existing.rows[0].profile_id===id)return send(res,200,{id:rid});return send(res,409,{error:'This entry ID is already in use.'});}const c=await pool.connect();try{await c.query('BEGIN');await c.query('INSERT INTO ratings(id,profile_id,movie_id,overall,watched_on,spoilers) VALUES($1,$2,$3,$4,$5,$6)',[rid,id,b.movieId,b.overall,b.watchedOn,b.spoilers]);for(const a of b.answers)await c.query('INSERT INTO answers(rating_id,question_version,aspect_id,score,skip_reason,note) VALUES($1,1,$2,$3,$4,$5)',[rid,a.aspectId,a.score,a.skipReason||null,a.note]);await c.query('DELETE FROM watchlist WHERE profile_id=$1 AND movie_id=$2',[id,b.movieId]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}return send(res,201,{id:rid});}
  if(req.method==='DELETE'&&url.pathname.startsWith('/api/ratings/')){const rid=url.pathname.split('/').pop();if(!/^[\da-f-]{36}$/.test(rid))return send(res,400,{error:'Invalid rating ID.'});const r=await pool.query('DELETE FROM ratings WHERE id=$1 AND profile_id=$2 RETURNING id',[rid,id]);return send(res,r.rowCount?200:404,r.rowCount?{ok:true}:{error:'Rating not found.'});}
  if(req.method==='POST'&&url.pathname==='/api/movies'){const b=await body(req);if(typeof b.title!=='string'||!b.title.trim()||b.title.length>160||!Number.isInteger(b.year)||b.year<1888||b.year>2200||typeof b.director!=='string'||b.director.length>160)throw Error('Enter a title, valid year and director (optional).');const existing=await pool.query('SELECT id FROM movies WHERE lower(title)=lower($1) AND year=$2',[b.title.trim(),b.year]);if(existing.rowCount)return send(res,200,{id:existing.rows[0].id});const mid=randomUUID();await pool.query('INSERT INTO movies(id,title,year,director) VALUES($1,$2,$3,$4)',[mid,b.title.trim(),b.year,b.director.trim()]);return send(res,201,{id:mid});}
  if(req.method==='POST'&&url.pathname==='/api/watchlist'){const b=await body(req);if(typeof b.saved!=='boolean')throw Error('Saved must be true or false.');const m=await pool.query('SELECT id FROM movies WHERE id=$1',[b.movieId]);if(!m.rowCount)throw Error('Film not found.');if(b.saved)await pool.query('INSERT INTO watchlist(profile_id,movie_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,b.movieId]);else await pool.query('DELETE FROM watchlist WHERE profile_id=$1 AND movie_id=$2',[id,b.movieId]);return send(res,200,{ok:true});}
  if(req.method==='PATCH'&&url.pathname==='/api/settings'){const b=await body(req);if(typeof b.contribute!=='boolean')throw Error('Contribution must be true or false.');await pool.query('UPDATE profiles SET contribute=$1 WHERE id=$2',[b.contribute,id]);return send(res,200,{ok:true});}
  if(req.method==='GET'&&url.pathname==='/api/taste'){const own=await getRatings(id);const taste=fitTaste(own);let recommendations=[];if(taste.ready){const aggregate=await pool.query(`WITH latest AS(SELECT DISTINCT ON(r.profile_id,r.movie_id) r.id,r.movie_id FROM ratings r JOIN profiles p ON p.id=r.profile_id WHERE p.contribute=true AND r.profile_id<>$1 ORDER BY r.profile_id,r.movie_id,r.created_at DESC) SELECT l.movie_id,a.aspect_id,avg(a.score)::float8 AS score,count(*)::integer AS sample FROM latest l JOIN answers a ON a.rating_id=l.id WHERE a.score IS NOT NULL GROUP BY l.movie_id,a.aspect_id HAVING count(*)>=3`,[id]);const grouped=new Map();for(const a of aggregate.rows){if(!grouped.has(a.movie_id))grouped.set(a.movie_id,[]);grouped.get(a.movie_id).push(a);}const seen=new Set(own.map(r=>r.movieId));for(const [mid,as] of grouped){if(seen.has(mid)||!modelAspectIds.every(id=>as.some(a=>a.aspect_id===id)))continue;const score=taste.intercept+taste.weights.reduce((s,w)=>s+w.coefficient*as.find(a=>a.aspect_id===w.id).score,0);recommendations.push({movieId:mid,predicted:Math.max(0.5,Math.min(5,score)),sample:Math.min(...as.map(a=>a.sample)),reason:'Estimated from your craft associations and opt-in viewers’ aspect scores. Not a certainty.'});}recommendations.sort((a,b)=>b.predicted-a.predicted);}
  const films=(await pool.query(movieSelect)).rows;const early=earlyRecommendations(buildFilmIndex(films),own);return send(res,200,{...taste,recommendations:recommendations.slice(0,8),earlyRecommendations:early,catalogue:catalogueMeta});}
  if(req.method==='GET'&&url.pathname==='/api/export'){return send(res,200,{schemaVersion:1,questionVersion:1,exportedAt:new Date().toISOString(),ratings:await getRatings(id),watchlist:(await pool.query('SELECT movie_id FROM watchlist WHERE profile_id=$1',[id])).rows.map(r=>r.movie_id),movies:(await pool.query(movieSelect)).rows});}
  if(req.method==='DELETE'&&url.pathname==='/api/profile'){await pool.query('DELETE FROM profiles WHERE id=$1',[id]);res.setHeader('Set-Cookie','af_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return send(res,200,{ok:true});}
  return send(res,404,{error:'Endpoint not found.'});
 }
 if(req.method!=='GET')return send(res,405,{error:'Method not allowed.'});let rel=decodeURIComponent(url.pathname);if(rel==='/')rel='/index.html';const full=path.resolve(root,'public','.'+rel);if(!full.startsWith(path.join(root,'public')+path.sep))return send(res,403,{error:'Forbidden.'});const ext=path.extname(full);const content=await fs.readFile(full);res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml'}[ext]||'application/octet-stream'),'Cache-Control':'no-cache'});res.end(content);
 }catch(e){const status=e.code==='ENOENT'?404:e.status||400;if(!e.code&&!e.status)console.error(e.message);if(e.code&&e.code!=='ENOENT')return send(res,500,{error:'Storage could not complete this request. Your answers have not been marked as saved.'});send(res,status,{error:e.code==='ENOENT'?'Not found.':e.message});}
}
export default handleRequest;
export const server=http.createServer(handleRequest);
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const port=Number(process.env.PORT||3000);server.listen(port,'0.0.0.0',()=>console.log(`Afterframe listening on ${port} · PostgreSQL connected`));
 const cleanup=setInterval(()=>{for(const [id,e]of limiter)if(Date.now()-e.t>120000)limiter.delete(id);pool.query('DELETE FROM sessions WHERE expires_at<now()').catch(()=>{});},600000);cleanup.unref();
 async function shutdown(){clearInterval(cleanup);server.close();await pool.end();process.exit(0);}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
}

