import fs from 'node:fs/promises';
import path from 'node:path';
import {randomBytes,randomUUID,createHash,createHmac,hkdfSync,timingSafeEqual,createCipheriv,createDecipheriv} from 'node:crypto';
import {hash as argonHash,verify as argonVerify,Algorithm} from '@node-rs/argon2';
import {passwordProblem} from '../public/password-policy.js';

export class AuthError extends Error {constructor(status,code,message){super(message);this.status=status;this.code=code;}}
const fail=(status,code,message)=>{throw new AuthError(status,code,message)};
const digest=s=>createHash('sha256').update(s).digest('hex');
const fixedEqual=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const cookie=(req,name)=>(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(name+'='))?.slice(name.length+1);
const genericMail={message:'If this address is eligible, instructions will arrive shortly. Check your inbox and spam folder.'};
const common=new Set(['passwordpassword','123456789012345','qwertyqwertyqwerty','afterframeafterframe','letmeinletmeinletmein','aaaaaaaaaaaaaaa']);
const options={algorithm:Algorithm.Argon2id,memoryCost:65536,timeCost:3,parallelism:1,outputLen:32};
let running=0;
async function boundedHashJob(fn){if(running>=4)fail(503,'AUTH_BUSY','Sign-in is busy. Please try again shortly.');running++;try{return await fn()}finally{running--}}
export async function createAuth(pool,{root,production,origin,runMigrations=true}) {
  if (typeof origin === 'string') {
    try { origin = new URL(origin).origin; } catch {}
  }
  const parsedOrigin=new URL(origin);if(parsedOrigin.origin!==origin||!['http:','https:'].includes(parsedOrigin.protocol))throw Error('APP_ORIGIN must be an exact http(s) origin with no path or trailing slash.');
  if (production && (!origin.startsWith('https://') || !process.env.AUTH_SECRET))
    throw Error('Production authentication requires HTTPS APP_ORIGIN and AUTH_SECRET.');
  const mailDir=path.join(root,'.dev-mail');let secret;
  if(process.env.AUTH_SECRET){secret=Buffer.from(process.env.AUTH_SECRET,'base64');if(secret.length<32)throw Error('AUTH_SECRET must be base64 encoding at least 32 random bytes.');}
  else {
    try {
      await fs.mkdir(mailDir,{recursive:true,mode:0o700});
      try{secret=await fs.readFile(path.join(mailDir,'.key'))}catch{secret=randomBytes(32);await fs.writeFile(path.join(mailDir,'.key'),secret,{mode:0o600})}
    } catch {
      secret=randomBytes(32);
    }
  }
  if(!secret||secret.length<32)throw Error('Authentication key material is invalid.');
  const csrfKey=Buffer.from(hkdfSync('sha256',secret,Buffer.alloc(0),'afterframe/csrf/v1',32));
  const mailKey=Buffer.from(hkdfSync('sha256',secret,Buffer.alloc(0),'afterframe/mail/v1',32));
  const mac=s=>createHmac('sha256',csrfKey).update(s).digest('hex');
  const sessionName=production?'__Host-af_auth':'af_auth';const preauthName=production?'__Host-af_preauth':'af_preauth';
  const dummyHash=await boundedHashJob(()=>argonHash(randomBytes(32).toString('hex'),options));
  try {
    await pool.query(await fs.readFile(path.join(root,'db/auth-schema.sql'),'utf8'));
  } catch (err) {
    if (runMigrations) throw err;
  }
  await pool.query('SELECT id FROM auth_accounts LIMIT 0');await pool.query('SELECT token_hash FROM auth_sessions LIMIT 0');
  const response=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
  function appendCookie(res,value){const old=res.getHeader('Set-Cookie');res.setHeader('Set-Cookie',[...(Array.isArray(old)?old:old?[old]:[]),value]);}
  function setCookie(res,name,value,seconds){appendCookie(res,`${name}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${seconds}${production?'; Secure':''}`);}
  const summary=a=>({id:a.id,profileId:a.profile_id,email:a.email,displayName:a.display_name,username:a.username,bio:a.bio,emailVerified:!!a.email_verified_at,createdAt:a.created_at});
  function email(value){if(typeof value!=='string')fail(400,'INVALID_EMAIL','Enter a valid email address.');const e=value.trim().toLowerCase();if(e.length>254||! /^[A-Za-z0-9.!#$%&'*+\/=?^_`{|}~-]+@(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/i.test(e)||e.includes('..')||e.split('@')[0].length>64||e.startsWith('.')||e.split('@')[0].endsWith('.'))fail(400,'INVALID_EMAIL','Enter a valid email address.');return e;}
  function name(value){if(typeof value!=='string'||[...value.trim()].length<2||[...value.trim()].length>60||/[\p{Cc}\p{Cf}]/u.test(value))fail(400,'INVALID_NAME','Use a display name of 2–60 characters.');return value.trim();}
  async function validateNewPassword(password){const problem=passwordProblem(password);if(problem)fail(400,'PASSWORD_POLICY',problem);if(common.has(password.toLowerCase()))fail(400,'PASSWORD_BLOCKED','Choose a less common passphrase.');
    if(production || process.env.HIBP_CHECK==='true') {const sha=createHash('sha1').update(password,'utf8').digest('hex').toUpperCase();try{const r=await fetch('https://api.pwnedpasswords.com/range/'+sha.slice(0,5),{headers:{'Add-Padding':'true','User-Agent':'Afterframe password screening'},signal:AbortSignal.timeout(6000)});if(!r.ok)throw Error('unavailable');const rows=(await r.text()).split(/\r?\n/);if(rows.some(line=>{const [suffix,count]=line.split(':');return suffix===sha.slice(5)&&Number(count)>0}))fail(400,'PASSWORD_BLOCKED','This password appears in breach data. Choose another passphrase.');}catch(e){if(e instanceof AuthError)throw e;fail(503,'PASSWORD_SCREEN_UNAVAILABLE','Password screening is temporarily unavailable. Please try again later.');}}
  }
  async function limits(req,scope,identity='',ipMax=30,idMax=8,seconds=900){const ip=req.headers?.['x-forwarded-for']?.split(',')[0]?.trim()||req.headers?.['x-real-ip']||req.socket?.remoteAddress||'unknown';for(const [key,max] of [[`ip:${ip}`,ipMax],...(identity?[[`identity:${identity}`,idMax]]:[])]){const start=new Date(Math.floor(Date.now()/(seconds*1000))*seconds*1000);const r=await pool.query(`INSERT INTO auth_rate_limits(key_hash,scope,window_start) VALUES($1,$2,$3) ON CONFLICT(key_hash,scope,window_start) DO UPDATE SET hits=auth_rate_limits.hits+1 RETURNING hits`,[mac(key),scope,start]);if(r.rows[0].hits>max)fail(429,'AUTH_RATE_LIMIT','Too many attempts. Please wait before trying again.');}}
  async function getSession(req){if(req._afAuth!==undefined)return req._afAuth;const raw=cookie(req,sessionName);if(!raw||!/^[a-f0-9]{64}$/.test(raw)){req._afAuth=null;return null;}const r=await pool.query(`SELECT a.*,s.token_hash,s.created_at AS session_created_at,s.expires_at AS session_expires_at FROM auth_sessions s JOIN auth_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.credentials_version=a.credentials_version AND s.expires_at>now() AND s.last_seen_at>now()-interval '12 hours' AND a.email_verified_at IS NOT NULL`,[digest(raw)]);if(!r.rowCount){req._afAuth=null;return null;}await pool.query("UPDATE auth_sessions SET last_seen_at=now() WHERE token_hash=$1 AND last_seen_at<now()-interval '5 minutes'",[digest(raw)]);req._afAuth={account:r.rows[0],raw};return req._afAuth;}
  async function requireAccount(req){const s=await getSession(req);if(!s)fail(401,'AUTH_REQUIRED','Sign in to use your journal.');return s.account;}
  function validPreauth(raw){if(!raw)return false;const [expires,nonce,sig]=raw.split('.');return /^\d+$/.test(expires||'')&&Number(expires)>Date.now()&&Number(expires)<Date.now()+21*60*1000&&/^[a-f0-9]{64}$/.test(nonce||'')&&fixedEqual(sig,mac('preauth:'+expires+'.'+nonce));}
  async function csrfToken(req,res){const s=await getSession(req);if(s)return mac('session:'+s.raw);let raw=cookie(req,preauthName);if(!validPreauth(raw)){const unsigned=(Date.now()+20*60*1000)+'.'+randomBytes(32).toString('hex');raw=unsigned+'.'+mac('preauth:'+unsigned);setCookie(res,preauthName,raw,1200);}return mac('challenge:'+raw);}
  async function assertMutation(req){if(req.headers.origin!==origin||req.headers['sec-fetch-site']==='cross-site')fail(403,'ORIGIN_REJECTED','Request origin is not allowed.');if(req.method!=='DELETE'&&!req.headers['content-type']?.startsWith('application/json'))fail(415,'JSON_REQUIRED','Send application/json.');const s=await getSession(req);const raw=cookie(req,preauthName);const expected=s?mac('session:'+s.raw):validPreauth(raw)?mac('challenge:'+raw):null;if(!expected||!fixedEqual(req.headers['x-csrf-token'],expected))fail(403,'CSRF_REJECTED','Refresh the page before trying again.');}
  async function body(req){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>16384)fail(413,'BODY_TOO_LARGE','Request is too large.');chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{fail(400,'INVALID_JSON','Send valid JSON.')}}
  function seal(obj){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',mailKey,iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(obj),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64');}
  function unseal(value){const b=Buffer.from(value,'base64');const d=createDecipheriv('aes-256-gcm',mailKey,b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([d.update(b.subarray(28)),d.final()]).toString('utf8'));}
  async function audit(event,accountId=null,c=pool){await c.query('INSERT INTO auth_audit(id,account_id,event) VALUES($1,$2,$3)',[randomUUID(),accountId,event]);}
  async function queueToken(c,a,purpose){const raw=randomBytes(32).toString('hex');await c.query('DELETE FROM auth_email_tokens WHERE account_id=$1 AND purpose=$2',[a.id,purpose]);await c.query(`INSERT INTO auth_email_tokens(token_hash,account_id,purpose,expires_at) VALUES($1,$2,$3,now()+$4::interval)`,[digest(raw),a.id,purpose,purpose==='verify'?'24 hours':'30 minutes']);const url=origin+'/landing.html#'+purpose+'='+raw;await c.query('INSERT INTO auth_mail_outbox(id,account_id,encrypted_payload) VALUES($1,$2,$3)',[randomUUID(),a.id,seal({to:a.email,subject:purpose==='verify'?'Verify your Afterframe email':'Reset your Afterframe password',text:`${purpose==='verify'?'Verify your email':'Reset your password'}: ${url}\n\nThis link is single-use and expires in ${purpose==='verify'?'24 hours':'30 minutes'}. If you did not request it, ignore this message.`})]);setTimeout(()=>{mailTick().catch(()=>{})},50);}
  async function issueSession(req,res,a,remember){const raw=randomBytes(32).toString('hex');const seconds=remember?30*86400:7*86400;const old=await getSession(req);const c=await pool.connect();try{await c.query('BEGIN');if(old)await c.query('DELETE FROM auth_sessions WHERE token_hash=$1',[digest(old.raw)]);const r=await c.query(`INSERT INTO auth_sessions(token_hash,account_id,credentials_version,expires_at) SELECT $1,id,credentials_version,now()+$3::interval FROM auth_accounts WHERE id=$2 AND credentials_version=$4 AND email_verified_at IS NOT NULL RETURNING account_id`,[digest(raw),a.id,seconds+' seconds',a.credentials_version]);if(!r.rowCount)fail(401,'INVALID_CREDENTIALS','Email or password is incorrect.');await audit('login_success',a.id,c);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}setCookie(res,sessionName,raw,seconds);setCookie(res,preauthName,'',0);return mac('session:'+raw);}
  async function checkPassword(a,password){if(typeof password!=='string'||new TextEncoder().encode(password).length>512||passwordProblem(password))return false;return boundedHashJob(()=>argonVerify(a?.password_hash||dummyHash,password));}
  async function withTransaction(fn){const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
  async function reauthenticate(req,password){const a=await requireAccount(req);await limits(req,'reauth',a.id,20,6);if(!await checkPassword(a,password))fail(401,'REAUTH_FAILED','Current password is incorrect.');return a;}
  async function mailTick(){const c=await pool.connect();let job;try{await c.query('BEGIN');const r=await c.query(`SELECT * FROM auth_mail_outbox WHERE sent_at IS NULL AND attempts<5 AND available_at<=now() AND (locked_until IS NULL OR locked_until<now()) ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`);job=r.rows[0];if(job)await c.query("UPDATE auth_mail_outbox SET locked_until=now()+interval '1 minute',attempts=attempts+1 WHERE id=$1",[job.id]);await c.query('COMMIT');}catch{await c.query('ROLLBACK');return}finally{c.release()}if(!job)return;try{const payload=unseal(job.encrypted_payload);console.log(`[AUTH MAIL] To: ${payload.to} | Subject: ${payload.subject}\n${payload.text}`);if(process.env.RESEND_API_KEY&&process.env.MAIL_FROM){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Authorization':'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':job.id},body:JSON.stringify({from:process.env.MAIL_FROM,...payload}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('MAIL_DELIVERY_REJECTED');}else{try{await fs.mkdir(mailDir,{recursive:true,mode:0o700});await fs.writeFile(path.join(mailDir,job.id+'.json'),JSON.stringify(payload,null,2),{mode:0o600});}catch{}}await pool.query('UPDATE auth_mail_outbox SET sent_at=now(),locked_until=NULL,last_error_code=NULL WHERE id=$1',[job.id]);}catch{await pool.query("UPDATE auth_mail_outbox SET locked_until=NULL,available_at=now()+interval '1 minute',last_error_code='DELIVERY_FAILED' WHERE id=$1",[job.id]);}}
  let mailBusy=false;const mailTimer=setInterval(async()=>{if(mailBusy)return;mailBusy=true;try{await mailTick()}catch{}finally{mailBusy=false}},1500);mailTimer.unref();
  const cleanup=setInterval(()=>pool.query(`DELETE FROM auth_email_tokens WHERE expires_at<now();DELETE FROM auth_sessions WHERE expires_at<now() OR last_seen_at<now()-interval '12 hours';DELETE FROM auth_rate_limits WHERE window_start<now()-interval '2 hours';DELETE FROM auth_mail_outbox WHERE sent_at<now()-interval '24 hours' OR created_at<now()-interval '7 days';DELETE FROM auth_audit WHERE created_at<now()-interval '90 days'`).catch(()=>{}),300000);cleanup.unref();
  async function handle(req,res,url){if(!url.pathname.startsWith('/api/auth/'))return false;try{
    if(req.method==='GET'&&url.pathname==='/api/auth/session'){const s=await getSession(req);response(res,200,{authenticated:!!s,account:s?summary(s.account):null,csrfToken:await csrfToken(req,res)});return true;}
    if(!['POST','PATCH','DELETE'].includes(req.method)){response(res,405,{error:'Method not allowed.'});return true;}
    await assertMutation(req);const b=await body(req);const route=url.pathname.slice('/api/auth/'.length);
    if(route==='register'&&req.method==='POST'){const e=email(b.email),display=name(b.displayName);await limits(req,'register',e,20,3,3600);await validateNewPassword(b.password);const hashed=await boundedHashJob(()=>argonHash(b.password,options));await withTransaction(async c=>{const existing=await c.query('SELECT * FROM auth_accounts WHERE email=$1 FOR UPDATE',[e]);if(existing.rowCount){if(!existing.rows[0].email_verified_at)await queueToken(c,existing.rows[0],'verify');return;}const id=randomUUID(),pid=randomUUID(),username='filmgoer_'+randomBytes(5).toString('hex');await c.query('INSERT INTO profiles(id) VALUES($1)',[pid]);await c.query('INSERT INTO auth_accounts(id,profile_id,email,password_hash,display_name,username) VALUES($1,$2,$3,$4,$5,$6)',[id,pid,e,hashed,display,username]);await queueToken(c,{id,email:e},'verify');await audit('registration',id,c);});response(res,202,genericMail);return true;}
    if(route==='login'&&req.method==='POST'){const e=email(b.email);await limits(req,'login',e);const a=(await pool.query('SELECT * FROM auth_accounts WHERE email=$1',[e])).rows[0];const valid=await checkPassword(a,b.password);if(!a||!valid||!a.email_verified_at){await audit('login_failed');fail(401,'INVALID_CREDENTIALS','Email or password is incorrect, or email verification is incomplete.');}const csrf=await issueSession(req,res,a,b.remember===true);response(res,200,{account:summary(a),csrfToken:csrf});return true;}
    if(['forgot','resend'].includes(route)&&req.method==='POST'){const e=email(b.email);await limits(req,route,e,20,3,3600);await withTransaction(async c=>{const a=(await c.query('SELECT * FROM auth_accounts WHERE email=$1 FOR UPDATE',[e])).rows[0];if(a&&(route==='forgot'?!!a.email_verified_at:!a.email_verified_at))await queueToken(c,a,route==='forgot'?'reset':'verify');});response(res,202,genericMail);return true;}
    if(route==='verify'&&req.method==='POST'){await limits(req,'verify','',30);if(typeof b.token!=='string'||!/^[a-f0-9]{64}$/.test(b.token))fail(400,'INVALID_LINK','This verification link is invalid or expired.');await withTransaction(async c=>{const t=(await c.query("SELECT * FROM auth_email_tokens WHERE token_hash=$1 AND purpose='verify' AND expires_at>now() FOR UPDATE",[digest(b.token)])).rows[0];if(!t)fail(400,'INVALID_LINK','This verification link is invalid or expired.');await c.query('UPDATE auth_accounts SET email_verified_at=now(),updated_at=now() WHERE id=$1',[t.account_id]);await c.query('DELETE FROM auth_email_tokens WHERE account_id=$1 AND purpose=$2',[t.account_id,'verify']);await audit('email_verified',t.account_id,c);});response(res,200,{message:'Email verified. You can now sign in.'});return true;}
    if(route==='reset'&&req.method==='POST'){await limits(req,'reset','',20);await validateNewPassword(b.password);if(typeof b.token!=='string'||!/^[a-f0-9]{64}$/.test(b.token))fail(400,'INVALID_LINK','This reset link is invalid or expired.');const hashed=await boundedHashJob(()=>argonHash(b.password,options));await withTransaction(async c=>{const t=(await c.query("SELECT * FROM auth_email_tokens WHERE token_hash=$1 AND purpose='reset' AND expires_at>now() FOR UPDATE",[digest(b.token)])).rows[0];if(!t)fail(400,'INVALID_LINK','This reset link is invalid or expired.');await c.query('UPDATE auth_accounts SET password_hash=$1,credentials_version=credentials_version+1,updated_at=now() WHERE id=$2',[hashed,t.account_id]);await c.query('DELETE FROM auth_sessions WHERE account_id=$1',[t.account_id]);await c.query('DELETE FROM auth_email_tokens WHERE account_id=$1',[t.account_id]);await audit('password_reset',t.account_id,c);});setCookie(res,sessionName,'',0);response(res,200,{message:'Password reset. Sign in again on each device.'});return true;}
    if(route==='logout'&&req.method==='POST'){const s=await getSession(req);if(s){await pool.query('DELETE FROM auth_sessions WHERE token_hash=$1',[digest(s.raw)]);await audit('logout',s.account.id);}setCookie(res,sessionName,'',0);response(res,200,{ok:true});return true;}
    if(route==='profile'&&req.method==='PATCH'){const a=await requireAccount(req);const display=name(b.displayName);if(typeof b.username!=='string'||! /^[a-z0-9_]{3,24}$/.test(b.username))fail(400,'INVALID_USERNAME','Use 3–24 lowercase letters, numbers or underscores.');if(['admin','administrator','support','security','system','afterframe','root','moderator'].includes(b.username))fail(409,'USERNAME_TAKEN','That username is unavailable.');if(typeof b.bio!=='string'||[...b.bio].length>500||/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F\p{Cf}\p{Cs}]/u.test(b.bio))fail(400,'INVALID_BIO','Keep your bio under 500 characters.');if(Object.keys(b).some(k=>!['displayName','username','bio'].includes(k)))fail(400,'INVALID_FIELD','Only name, username and bio can be changed here.');try{const r=await pool.query('UPDATE auth_accounts SET display_name=$1,username=$2,bio=$3,updated_at=now() WHERE id=$4 RETURNING *',[display,b.username,b.bio,a.id]);response(res,200,{account:summary(r.rows[0])});}catch(e){if(e.code==='23505')fail(409,'USERNAME_TAKEN','That username is unavailable.');throw e;}return true;}
    if(route==='password'&&req.method==='POST'){const a=await reauthenticate(req,b.currentPassword);await limits(req,'password_change',a.id,15,5);await validateNewPassword(b.newPassword);const h=await boundedHashJob(()=>argonHash(b.newPassword,options));await withTransaction(async c=>{const changed=await c.query('UPDATE auth_accounts SET password_hash=$1,credentials_version=credentials_version+1,updated_at=now() WHERE id=$2 AND credentials_version=$3 RETURNING id',[h,a.id,a.credentials_version]);if(!changed.rowCount)fail(401,'REAUTH_FAILED','Please sign in again before changing your password.');await c.query('DELETE FROM auth_sessions WHERE account_id=$1',[a.id]);await c.query('DELETE FROM auth_email_tokens WHERE account_id=$1',[a.id]);await audit('password_changed',a.id,c);});setCookie(res,sessionName,'',0);response(res,200,{message:'Password changed. Sign in again on each device.'});return true;}
    if(route==='logout-all'&&req.method==='POST'){const a=await reauthenticate(req,b.currentPassword);await pool.query('DELETE FROM auth_sessions WHERE account_id=$1',[a.id]);await audit('logout_all',a.id);setCookie(res,sessionName,'',0);response(res,200,{ok:true});return true;}
    if(route==='account'&&req.method==='DELETE'){const a=await reauthenticate(req,b.currentPassword);await withTransaction(async c=>{const current=(await c.query('SELECT credentials_version FROM auth_accounts WHERE id=$1 FOR UPDATE',[a.id])).rows[0];if(!current||current.credentials_version!==a.credentials_version)fail(401,'REAUTH_FAILED','Please sign in again before deleting your account.');await audit('account_deleted',a.id,c);await c.query('DELETE FROM profiles WHERE id=$1',[a.profile_id]);});setCookie(res,sessionName,'',0);response(res,200,{ok:true});return true;}
    response(res,404,{error:'Authentication endpoint not found.'});return true;
  }catch(e){if(e instanceof AuthError)response(res,e.status,{error:e.message,code:e.code});else{console.error('Authentication request error:', e);response(res,500,{error:'Authentication could not complete this request.',detail:e?.message||String(e)});}return true;}}
  return {handle,getSession,requireAccount,assertMutation,close(){clearInterval(mailTimer);clearInterval(cleanup)}};
}
