import fs from 'node:fs/promises';import {gunzipSync} from 'node:zlib';import {buildFilmIndex,earlyRecommendations} from '../public/recommend.js';import {fitTaste,modelAspectIds} from '../public/model.js';import {rankHybrid} from './hybrid.mjs';
export async function createRecommender({pool,root,movieSelect,getRatings,populationPrior}){
 const historical=JSON.parse(gunzipSync(Buffer.from(await fs.readFile(root+'/catalogue/collaborative.json.gz.b64','utf8'),'base64')).toString('utf8'));let filmsMemo=null,filmsJob=null,revision=0;const profiles=new Map(),jobs=new Map();
 async function films(){if(filmsMemo&&filmsMemo.until>Date.now())return filmsMemo;if(filmsJob?.revision===revision)return filmsJob.promise;const generation=revision;const promise=(async()=>{const movies=(await pool.query(movieSelect)).rows;const value={until:Date.now()+60000,movies,index:buildFilmIndex(movies)};if(generation===revision)filmsMemo=value;return value;})();filmsJob={revision:generation,promise};try{return await promise}finally{if(filmsJob?.promise===promise)filmsJob=null;}}
 async function profile(id){const key=revision+':'+id;if(jobs.has(key))return jobs.get(key);const promise=buildProfile(id).finally(()=>jobs.delete(key));jobs.set(key,promise);return promise;}
 async function buildProfile(id){const generation=revision;let cached=profiles.get(id);if(cached&&cached.until>Date.now())return cached.value;
  const own=await getRatings(id),prior=await populationPrior(),taste=fitTaste(own,{prior:prior.coefficients,priorSource:prior.source}),f=await films();let aspects=[];
  if(taste.ready){const r=await pool.query(`WITH latest AS(SELECT DISTINCT ON(r.profile_id,r.movie_id) r.id,r.movie_id FROM ratings r JOIN profiles p ON p.id=r.profile_id WHERE p.contribute=true AND r.profile_id<>$1 ORDER BY r.profile_id,r.movie_id,r.created_at DESC) SELECT l.movie_id AS "movieId",a.aspect_id AS "aspectId",avg(a.score)::float8 AS score,count(*)::integer AS sample FROM latest l JOIN answers a ON a.rating_id=l.id WHERE a.score IS NOT NULL GROUP BY l.movie_id,a.aspect_id HAVING count(*)>=3`,[id]);aspects=r.rows;}
  // Public profile response contains numeric aggregates only, never other users' notes or IDs.
  const recommendations=rankHybrid(f.index,own,{neighbors:historical.neighbors,taste,aspects,limit:8});const craft=aspects.reduce((map,a)=>{if(!map.has(a.movieId))map.set(a.movieId,[]);map.get(a.movieId).push(a);return map;},new Map());const seen=new Set(own.map(r=>r.movieId));const estimates=[];
  if(taste.ready)for(const [mid,a]of craft){if(seen.has(mid)||!modelAspectIds.every(key=>a.some(v=>v.aspectId===key)))continue;estimates.push({movieId:mid,predicted:Math.max(.5,Math.min(5,taste.intercept+taste.weights.reduce((s,w)=>s+w.coefficient*a.find(v=>v.aspectId===w.id).score,0))),sample:Math.min(...a.map(x=>x.sample)),reason:'Experimental estimate from your associations and opt-in viewers’ numerical craft scores.'});}
  estimates.sort((a,b)=>b.predicted-a.predicted);
  const value={own,taste,aspects,public:{...taste,recommendations:estimates.slice(0,8),hybridRecommendations:recommendations,earlyRecommendations:earlyRecommendations(f.index,own),algorithm:{version:3,collaborativeSource:historical.source,historicalUsers:historical.userCount,accuracyValidated:false}}};
  if(generation===revision){profiles.delete(id);if(profiles.size>=500)profiles.delete(profiles.keys().next().value);profiles.set(id,{until:Date.now()+60000,value});}return value;
 }
 return {films,profile,invalidate(){revision++;filmsMemo=null;profiles.clear();},async discover(id,predicate){const [p,f]=await Promise.all([profile(id),films()]);const matched=f.movies.filter(predicate);const candidateIds=new Set(matched.map(m=>m.id));return rankHybrid(f.index,p.own,{neighbors:historical.neighbors,taste:p.taste,aspects:p.aspects,limit:8,discovery:true,candidateIds});}};
}
