import {randomUUID} from 'node:crypto';
const uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(v);
const fail=(status,message)=>{throw Object.assign(Error(message),{status})};
const person=a=>({username:a.username,displayName:a.display_name});
const only=(body,keys)=>{if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!keys.includes(k)))fail(400,'Unexpected request fields.');};
const username=v=>{if(typeof v!=='string')fail(400,'Use a username.');const name=v.trim().replace(/^@/,'').toLowerCase();if(!/^[a-z0-9_]{3,24}$/.test(name))fail(400,'Use a valid username.');return name;};
const text=(v,max,required=false)=>{if(typeof v!=='string'||[...v].length>max||/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F-\u009F\p{Cf}\p{Cs}]/u.test(v)||required&&!v.trim())fail(400,`Use ${required?'1–':'at most '}${max} characters of plain text.`);return v.trim();};
const boolean=v=>{if(typeof v!=='boolean')fail(400,'Use true or false.');return v;};
const escapeLike=v=>v.replace(/[\\%_]/g,'\\$&');
const offsetOf=url=>{const v=url.searchParams.get('offset')||'0';if(!/^\d{1,4}$/.test(v)||Number(v)>5000)fail(400,'Invalid page offset.');return Number(v);};
const cursorOf=url=>{const value=url.searchParams.get('cursor');if(!value)return {at:null,id:null};if(value.length>256||!/^[A-Za-z0-9_-]+$/.test(value))fail(400,'Invalid feed cursor.');try{const c=JSON.parse(Buffer.from(value,'base64url').toString());if(!uuid(c.id)||typeof c.at!=='string'||!/^\d{4}-\d\d-\d\dT/.test(c.at)||!Number.isFinite(Date.parse(c.at)))throw Error();return {at:c.at,id:c.id};}catch{fail(400,'Invalid feed cursor.');}};
const cursor=row=>Buffer.from(JSON.stringify({at:row.cursor_at||row.at,id:row.id})).toString('base64url');
const blocked=(a,b)=>`EXISTS(SELECT 1 FROM social_blocks sb WHERE (sb.owner_id=${a} AND sb.blocked_id=${b}) OR (sb.owner_id=${b} AND sb.blocked_id=${a}))`;
const friends=(a,b)=>`EXISTS(SELECT 1 FROM friend_connections fc WHERE fc.status='accepted' AND ((fc.requester_id=${a} AND fc.recipient_id=${b}) OR (fc.requester_id=${b} AND fc.recipient_id=${a}))) AND NOT ${blocked(a,b)}`;
const viewable=(viewer,owner)=>`(${viewer}=${owner} OR (${friends(viewer,owner)}))`;
const movieColumns=`m.id AS "movieId",m.title,m.year,m.poster,m.director,m.genres,m.runtime`;
export function createSocial({pool,auth,body,send}){
 async function transaction(fn){const c=await pool.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async function pairLock(c,a,b){const key=[a,b].sort().join(':');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[key]);}
 async function target(c,name){const a=(await c.query('SELECT id,username,display_name,discoverable FROM auth_accounts WHERE username=$1 AND email_verified_at IS NOT NULL',[username(name)])).rows[0];if(!a)fail(404,'This person is not available.');return a;}
 async function requireFriend(c,actor,targetId){if(actor===targetId)fail(400,'Choose a friend, not yourself.');const r=await c.query(`SELECT fc.id FROM friend_connections fc WHERE fc.status='accepted' AND ((fc.requester_id=$1 AND fc.recipient_id=$2) OR (fc.requester_id=$2 AND fc.recipient_id=$1)) AND NOT ${blocked('$1','$2')} FOR UPDATE`,[actor,targetId]);if(!r.rowCount)fail(403,'An accepted friendship is required.');}
 async function shareFor(actor,id,reveal=false){if(!uuid(id))fail(400,'Invalid review ID.');const r=await pool.query(`SELECT s.*,a.username,a.display_name,r.overall::float8,r.watched_on::text AS "watchedOn",${movieColumns},(SELECT count(*)::integer FROM social_review_likes l WHERE l.share_id=s.id AND ${viewable('l.account_id','s.owner_id')} AND NOT ${blocked('$1','l.account_id')}) AS "likeCount",EXISTS(SELECT 1 FROM social_review_likes l WHERE l.share_id=s.id AND l.account_id=$1) AS liked FROM social_review_shares s JOIN auth_accounts a ON a.id=s.owner_id JOIN ratings r ON r.id=s.rating_id JOIN movies m ON m.id=r.movie_id WHERE s.id=$2 AND ${viewable('$1','s.owner_id')}`,[actor,id]);if(!r.rowCount)fail(404,'Review unavailable.');const v=r.rows[0];return {internal:v,public:{id:v.id,ratingId:actor===v.owner_id?v.rating_id:undefined,author:person(v),movie:{id:v.movieId,title:v.title,year:v.year,poster:v.poster,director:v.director,genres:v.genres,runtime:v.runtime},overall:v.overall,watchedOn:v.watchedOn,reviewText:v.spoilers&&!reveal?null:v.review_text,spoilers:v.spoilers,likeCount:v.likeCount,liked:v.liked,isOwn:actor===v.owner_id,createdAt:v.created_at,updatedAt:v.updated_at}};}
 async function overview(actor){const r=(await pool.query(`SELECT a.discoverable,(SELECT count(*)::integer FROM friend_connections fc WHERE fc.status='accepted' AND (fc.requester_id=$1 OR fc.recipient_id=$1) AND NOT ${blocked('fc.requester_id','fc.recipient_id')}) AS friends,(SELECT count(*)::integer FROM friend_connections fc WHERE fc.status='pending' AND fc.recipient_id=$1 AND NOT ${blocked('fc.requester_id','fc.recipient_id')}) AS incoming,(SELECT count(*)::integer FROM friend_connections fc WHERE fc.status='pending' AND fc.requester_id=$1 AND NOT ${blocked('fc.requester_id','fc.recipient_id')}) AS outgoing,(SELECT count(*)::integer FROM friend_recommendations fr WHERE fr.recipient_id=$1 AND fr.seen_at IS NULL AND fr.dismissed_at IS NULL AND ${friends('fr.sender_id','fr.recipient_id')}) AS unread,(SELECT count(*)::integer FROM social_review_shares WHERE owner_id=$1) AS shared FROM auth_accounts a WHERE a.id=$1`,[actor])).rows[0];return r;}
 async function handle(req,res,url){if(!url.pathname.startsWith('/api/social/'))return false;
  const actor=await auth.requireAccount(req),id=actor.id;await auth.limits(req,req.method==='GET'?'social_read':'social_write',id,req.method==='GET'?600:120,req.method==='GET'?300:60,900);
  if(req.method!=='GET')await auth.assertMutation(req);const b=req.method==='GET'?null:await body(req);const route=url.pathname.slice('/api/social/'.length),parts=route.split('/');const out=(status,data)=>{send(res,status,data);return true;};
  if(route==='overview'&&req.method==='GET')return out(200,{...await overview(id),me:person(actor)});
  if(route==='settings'&&req.method==='PATCH'){only(b,['discoverable']);const value=boolean(b.discoverable);await pool.query('UPDATE auth_accounts SET discoverable=$1,updated_at=now() WHERE id=$2',[value,id]);return out(200,{discoverable:value});}
  if(route==='people'&&req.method==='GET'){const q=text((url.searchParams.get('q')||'').replace(/^@/,''),64,true).toLowerCase();if([...q].length<2)fail(400,'Search with at least two characters.');const offset=offsetOf(url),pattern='%'+escapeLike(q)+'%';const r=await pool.query(`SELECT a.username,a.display_name,fc.id AS connection_id,fc.status,fc.requester_id=$1 AS requested_by_me FROM auth_accounts a LEFT JOIN friend_connections fc ON (fc.requester_id=$1 AND fc.recipient_id=a.id) OR (fc.recipient_id=$1 AND fc.requester_id=a.id) WHERE a.id<>$1 AND a.email_verified_at IS NOT NULL AND a.discoverable=true AND NOT ${blocked('$1','a.id')} AND (a.username ILIKE $2 OR a.display_name ILIKE $2) ORDER BY (a.username=$3) DESC,a.username LIMIT 21 OFFSET $4`,[id,pattern,q,offset]);const rows=r.rows.slice(0,20);return out(200,{people:rows.map(v=>({...person(v),connectionId:v.connection_id,status:v.status,requestedByMe:v.requested_by_me})),nextOffset:r.rows.length>20?offset+20:null});}
  if(route==='friends'&&req.method==='GET'){const q=text((url.searchParams.get('q')||'').replace(/^@/,''),64),offset=offsetOf(url);const r=await pool.query(`SELECT fc.id,fc.updated_at,a.username,a.display_name FROM friend_connections fc JOIN auth_accounts a ON a.id=CASE WHEN fc.requester_id=$1 THEN fc.recipient_id ELSE fc.requester_id END WHERE fc.status='accepted' AND (fc.requester_id=$1 OR fc.recipient_id=$1) AND NOT ${blocked('fc.requester_id','fc.recipient_id')} AND (a.username ILIKE $2 OR a.display_name ILIKE $2) ORDER BY a.username LIMIT 21 OFFSET $3`,[id,'%'+escapeLike(q)+'%',offset]);return out(200,{friends:r.rows.slice(0,20).map(v=>({...person(v),connectionId:v.id,since:v.updated_at})),nextOffset:r.rows.length>20?offset+20:null});}
  if(route==='requests'&&req.method==='GET'){const direction=url.searchParams.get('direction')||'incoming';if(!['incoming','outgoing'].includes(direction))fail(400,'Invalid request direction.');const offset=offsetOf(url),mine=direction==='incoming'?'fc.recipient_id':'fc.requester_id',peer=direction==='incoming'?'fc.requester_id':'fc.recipient_id';const r=await pool.query(`SELECT fc.id,fc.created_at,a.username,a.display_name FROM friend_connections fc JOIN auth_accounts a ON a.id=${peer} WHERE ${mine}=$1 AND fc.status='pending' AND NOT ${blocked('fc.requester_id','fc.recipient_id')} ORDER BY fc.created_at DESC,fc.id DESC LIMIT 21 OFFSET $2`,[id,offset]);return out(200,{requests:r.rows.slice(0,20).map(v=>({...person(v),connectionId:v.id,createdAt:v.created_at})),nextOffset:r.rows.length>20?offset+20:null});}
  if(route==='requests'&&req.method==='POST'){only(b,['username']);await auth.limits(req,'friend_requests',id,30,10,3600);const result=await transaction(async c=>{const to=await target(c,b.username);if(to.id===id)fail(400,'You cannot add yourself.');await pairLock(c,id,to.id);if((await c.query(`SELECT 1 WHERE ${blocked('$1','$2')}`,[id,to.id])).rowCount||!to.discoverable)fail(404,'This person is not available.');const existing=(await c.query('SELECT * FROM friend_connections WHERE LEAST(requester_id,recipient_id)=LEAST($1::uuid,$2::uuid) AND GREATEST(requester_id,recipient_id)=GREATEST($1::uuid,$2::uuid) FOR UPDATE',[id,to.id])).rows[0];if(existing?.status==='accepted')fail(409,'You are already friends.');if(existing?.status==='pending')return {connectionId:existing.id,status:'pending',incoming:existing.recipient_id===id};if(existing&&Date.now()-new Date(existing.updated_at).getTime()<7*86400000)fail(429,'Please wait seven days before sending another request to this person.');if(existing){await c.query("UPDATE friend_connections SET requester_id=$1,recipient_id=$2,status='pending',created_at=now(),updated_at=now() WHERE id=$3",[id,to.id,existing.id]);return {connectionId:existing.id,status:'pending'};}const connectionId=randomUUID();await c.query("INSERT INTO friend_connections(id,requester_id,recipient_id,status) VALUES($1,$2,$3,'pending')",[connectionId,id,to.id]);return {connectionId,status:'pending'};});return out(201,result);}
  if(parts[0]==='requests'&&parts.length===2&&req.method==='PATCH'){only(b,['action']);if(!uuid(parts[1])||!['accept','decline'].includes(b.action))fail(400,'Invalid request action.');await transaction(async c=>{let fc=(await c.query('SELECT * FROM friend_connections WHERE id=$1 AND recipient_id=$2',[parts[1],id])).rows[0];if(!fc)fail(404,'Request unavailable.');await pairLock(c,fc.requester_id,fc.recipient_id);fc=(await c.query('SELECT * FROM friend_connections WHERE id=$1 AND recipient_id=$2 FOR UPDATE',[parts[1],id])).rows[0];if(!fc||fc.status!=='pending')fail(409,'This request is no longer pending.');if((await c.query(`SELECT 1 WHERE ${blocked('$1','$2')}`,[fc.requester_id,fc.recipient_id])).rowCount)fail(404,'Request unavailable.');await c.query('UPDATE friend_connections SET status=$1,updated_at=now() WHERE id=$2',[b.action==='accept'?'accepted':'declined',fc.id]);});return out(200,{ok:true});}
  if(parts[0]==='connections'&&parts.length===2&&req.method==='DELETE'){only(b,[]);if(!uuid(parts[1]))fail(400,'Invalid connection.');await transaction(async c=>{const fc=(await c.query(`SELECT * FROM friend_connections WHERE id=$1 AND ((status='accepted' AND (requester_id=$2 OR recipient_id=$2)) OR (status='pending' AND requester_id=$2))`,[parts[1],id])).rows[0];if(!fc)fail(404,'Connection unavailable.');await pairLock(c,fc.requester_id,fc.recipient_id);await c.query('DELETE FROM friend_connections WHERE id=$1 AND (requester_id=$2 OR recipient_id=$2)',[fc.id,id]);});return out(200,{ok:true});}
  if(route==='blocks'&&req.method==='GET'){const offset=offsetOf(url);const r=await pool.query('SELECT a.username,a.display_name FROM social_blocks sb JOIN auth_accounts a ON a.id=sb.blocked_id WHERE sb.owner_id=$1 ORDER BY a.username LIMIT 21 OFFSET $2',[id,offset]);return out(200,{people:r.rows.slice(0,20).map(person),nextOffset:r.rows.length>20?offset+20:null});}
  if(route==='blocks'&&['POST','DELETE'].includes(req.method)){only(b,['username']);await transaction(async c=>{const to=await target(c,b.username);if(to.id===id)fail(400,'You cannot block yourself.');await pairLock(c,id,to.id);if(req.method==='DELETE')await c.query('DELETE FROM social_blocks WHERE owner_id=$1 AND blocked_id=$2',[id,to.id]);else{await c.query('INSERT INTO social_blocks(owner_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,to.id]);await c.query('DELETE FROM friend_connections WHERE (requester_id=$1 AND recipient_id=$2) OR (requester_id=$2 AND recipient_id=$1)',[id,to.id]);}});return out(200,{ok:true});}
  if(parts[0]==='profile'&&parts.length===2&&req.method==='GET'){const to=await target(pool,decodeURIComponent(parts[1]));const r=await pool.query(`SELECT a.username,a.display_name,a.discoverable,$1=a.id AS "isOwn",(${friends('$1','a.id')}) AS "isFriend" FROM auth_accounts a WHERE a.id=$2 AND NOT ${blocked('$1','a.id')}`,[id,to.id]);const v=r.rows[0];if(!v||!v.discoverable&&!v.isFriend&&!v.isOwn)fail(404,'Profile unavailable.');let reviews=[];if(v.isFriend||v.isOwn){const offset=offsetOf(url);const rr=await pool.query(`SELECT s.id,r.overall::float8,r.watched_on::text AS "watchedOn",s.spoilers,CASE WHEN s.spoilers THEN NULL ELSE left(s.review_text,180) END AS excerpt,${movieColumns} FROM social_review_shares s JOIN ratings r ON r.id=s.rating_id JOIN movies m ON m.id=r.movie_id WHERE s.owner_id=$1 ORDER BY s.created_at DESC,s.id DESC LIMIT 21 OFFSET $2`,[to.id,offset]);reviews=rr.rows.slice(0,20).map(x=>({id:x.id,overall:x.overall,watchedOn:x.watchedOn,spoilers:x.spoilers,excerpt:x.excerpt,movie:{id:x.movieId,title:x.title,year:x.year,poster:x.poster}}));return out(200,{person:person(v),isFriend:v.isFriend,isOwn:v.isOwn,reviews,nextOffset:rr.rows.length>20?offset+20:null});}return out(200,{person:person(v),isFriend:false,isOwn:false,reviews:[],nextOffset:null});}
  if(parts[0]==='shares'&&parts.length===2){if(!uuid(parts[1]))fail(400,'Invalid journal entry.');const own=(await pool.query('SELECT id FROM ratings WHERE id=$1 AND profile_id=$2',[parts[1],actor.profile_id])).rows[0];if(!own)fail(404,'Journal entry unavailable.');if(req.method==='GET'){const s=(await pool.query('SELECT id,review_text AS "reviewText",spoilers FROM social_review_shares WHERE rating_id=$1 AND owner_id=$2',[own.id,id])).rows[0];return out(200,{share:s||null});}if(req.method==='PUT')fail(405,'Use POST to share a review.');if(req.method==='POST'){only(b,['reviewText','spoilers']);const review=text(b.reviewText,2000),spoilers=boolean(b.spoilers);const share=(await pool.query(`INSERT INTO social_review_shares(id,rating_id,owner_id,review_text,spoilers) SELECT $1,r.id,$3,$4,$5 FROM ratings r WHERE r.id=$2 AND r.profile_id=$6 ON CONFLICT(rating_id) DO UPDATE SET review_text=excluded.review_text,spoilers=excluded.spoilers,updated_at=now() RETURNING id`,[randomUUID(),own.id,id,review,spoilers,actor.profile_id])).rows[0];if(!share)fail(404,'Journal entry unavailable.');return out(200,{id:share.id});}if(req.method==='DELETE'){only(b,[]);await pool.query('DELETE FROM social_review_shares WHERE rating_id=$1 AND owner_id=$2',[own.id,id]);return out(200,{ok:true});}}
  if(parts[0]==='reviews'&&parts.length>=2){const share=await shareFor(id,parts[1],url.searchParams.get('reveal')==='1');const v=share.internal;if(parts.length===2&&req.method==='GET')return out(200,{review:share.public});
   if(parts[2]==='like'&&parts.length===3&&req.method==='POST'){only(b,['liked']);if(boolean(b.liked))await pool.query('INSERT INTO social_review_likes(share_id,account_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[v.id,id]);else await pool.query('DELETE FROM social_review_likes WHERE share_id=$1 AND account_id=$2',[v.id,id]);return out(200,{ok:true});}
   if(parts[2]==='comments'&&parts.length===3&&req.method==='GET'){const offset=offsetOf(url),reveal=url.searchParams.get('reveal')==='1';const rows=await pool.query(`SELECT c.id,a.username,a.display_name,c.created_at,c.author_id=$1 AS "isOwn",c.spoilers,CASE WHEN c.spoilers AND NOT $3 THEN NULL ELSE c.body END AS body FROM social_review_comments c JOIN auth_accounts a ON a.id=c.author_id WHERE c.share_id=$2 AND ${viewable('c.author_id','$4')} AND NOT ${blocked('$1','c.author_id')} ORDER BY c.created_at,c.id LIMIT 21 OFFSET $5`,[id,v.id,reveal,v.owner_id,offset]);return out(200,{comments:rows.rows.slice(0,20).map(c=>({id:c.id,author:person(c),createdAt:c.created_at,isOwn:c.isOwn,canDelete:c.isOwn||v.owner_id===id,body:c.body,spoilers:c.spoilers})),nextOffset:rows.rows.length>20?offset+20:null});}
   if(parts[2]==='comments'&&parts.length===3&&req.method==='POST'){only(b,['text','spoilers']);const commentId=randomUUID();await pool.query('INSERT INTO social_review_comments(id,share_id,author_id,body,spoilers) VALUES($1,$2,$3,$4,$5)',[commentId,v.id,id,text(b.text,500,true),boolean(b.spoilers)]);return out(201,{id:commentId});}
   if(parts[2]==='comments'&&parts.length===4&&req.method==='DELETE'){only(b,[]);if(!uuid(parts[3]))fail(400,'Invalid comment.');const removed=await pool.query('DELETE FROM social_review_comments WHERE id=$1 AND share_id=$2 AND (author_id=$3 OR $3=$4) RETURNING id',[parts[3],v.id,id,v.owner_id]);if(!removed.rowCount)fail(404,'Comment unavailable.');return out(200,{ok:true});}}
  if(route==='movie-ratings'&&req.method==='GET'){const ids=(url.searchParams.get('ids')||'').split(',').filter(Boolean);if(!ids.length||ids.length>60||ids.some(x=>x.length>100||/[\p{Cc}\p{Cf}]/u.test(x)))fail(400,'Request 1–60 movie IDs.');const r=await pool.query(`WITH latest AS(SELECT DISTINCT ON(r.movie_id,s.owner_id) s.id,s.owner_id,s.created_at,s.spoilers,s.review_text,r.movie_id,r.overall::float8,r.watched_on::text AS watched_on FROM social_review_shares s JOIN ratings r ON r.id=s.rating_id WHERE r.movie_id=ANY($2::text[]) AND ${friends('$1','s.owner_id')} ORDER BY r.movie_id,s.owner_id,r.created_at DESC,r.id DESC), ranked AS(SELECT *,row_number() OVER(PARTITION BY movie_id ORDER BY overall DESC,created_at DESC,id DESC) AS position,count(*) OVER(PARTITION BY movie_id)::integer AS total FROM latest) SELECT rr.*,a.username,a.display_name FROM ranked rr JOIN auth_accounts a ON a.id=rr.owner_id WHERE rr.position<=3 ORDER BY rr.movie_id,rr.position`,[id,[...new Set(ids)]]);const films={};for(const v of r.rows){films[v.movie_id]||={count:v.total,ratings:[]};films[v.movie_id].ratings.push({shareId:v.id,author:person(v),overall:v.overall,watchedOn:v.watched_on,spoilers:v.spoilers,excerpt:v.spoilers?null:v.review_text.slice(0,160)});}return out(200,{films});}
  if(route==='recommendations'&&req.method==='POST'){only(b,['username','movieId','message','spoilers','requestId']);if(typeof b.movieId!=='string'||b.movieId.length>100||!uuid(b.requestId))fail(400,'Choose a movie and a valid request ID.');const message=text(b.message,500),spoilers=boolean(b.spoilers);await auth.limits(req,'friend_recommendations',id,90,30,3600);const result=await transaction(async c=>{const to=await target(c,b.username);await pairLock(c,id,to.id);await requireFriend(c,id,to.id);if(!(await c.query('SELECT 1 FROM movies WHERE id=$1',[b.movieId])).rowCount)fail(404,'Movie unavailable.');const existing=(await c.query('SELECT * FROM friend_recommendations WHERE sender_id=$1 AND client_id=$2',[id,b.requestId])).rows[0];if(existing){if(existing.recipient_id!==to.id||existing.movie_id!==b.movieId||existing.message!==message||existing.spoilers!==spoilers)fail(409,'Request ID was already used.');return {id:existing.id,alreadySent:true};}const recommendationId=randomUUID();await c.query('INSERT INTO friend_recommendations(id,client_id,sender_id,recipient_id,movie_id,message,spoilers) VALUES($1,$2,$3,$4,$5,$6,$7)',[recommendationId,b.requestId,id,to.id,b.movieId,message,spoilers]);return {id:recommendationId};});return out(201,result);}
  if(route==='recommendations'&&req.method==='GET'){const direction=url.searchParams.get('direction')||'received';if(!['received','sent'].includes(direction))fail(400,'Invalid recommendation direction.');const offset=offsetOf(url),mine=direction==='received'?'fr.recipient_id':'fr.sender_id',peer=direction==='received'?'fr.sender_id':'fr.recipient_id';const rr=await pool.query(`SELECT fr.id,a.username,a.display_name,fr.created_at,fr.seen_at,fr.spoilers,fr.sender_id=$1 AS "isOwn",CASE WHEN fr.spoilers THEN NULL ELSE fr.message END AS message,${movieColumns} FROM friend_recommendations fr JOIN auth_accounts a ON a.id=${peer} JOIN movies m ON m.id=fr.movie_id WHERE ${mine}=$1 AND fr.dismissed_at IS NULL AND ${friends('fr.sender_id','fr.recipient_id')} ORDER BY fr.created_at DESC,fr.id DESC LIMIT 21 OFFSET $2`,[id,offset]);return out(200,{recommendations:rr.rows.slice(0,20).map(v=>({id:v.id,isOwn:v.isOwn,person:person(v),createdAt:v.created_at,seenAt:v.seen_at,spoilers:v.spoilers,message:v.message,movie:{id:v.movieId,title:v.title,year:v.year,poster:v.poster}})),nextOffset:rr.rows.length>20?offset+20:null});}
  if(parts[0]==='recommendations'&&parts.length===2){if(!uuid(parts[1]))fail(400,'Invalid recommendation.');const v=(await pool.query(`SELECT fr.* FROM friend_recommendations fr WHERE fr.id=$2 AND (fr.sender_id=$1 OR fr.recipient_id=$1) AND fr.dismissed_at IS NULL AND ${friends('fr.sender_id','fr.recipient_id')}`,[id,parts[1]])).rows[0];if(!v)fail(404,'Recommendation unavailable.');if(req.method==='GET')return out(200,{id:v.id,isOwn:v.sender_id===id,movieId:v.movie_id,message:v.spoilers&&url.searchParams.get('reveal')!=='1'?null:v.message,spoilers:v.spoilers});if(req.method==='PATCH'){only(b,['action']);if(v.recipient_id!==id||!['read','dismiss'].includes(b.action))fail(403,'Only the recipient can update this recommendation.');await pool.query(`UPDATE friend_recommendations SET ${b.action==='read'?'seen_at=COALESCE(seen_at,now())':'dismissed_at=now()'} WHERE id=$1 AND recipient_id=$2`,[v.id,id]);return out(200,{ok:true});}if(req.method==='DELETE'){only(b,[]);if(v.sender_id!==id)fail(403,'Only the sender can retract this recommendation.');await pool.query('DELETE FROM friend_recommendations WHERE id=$1 AND sender_id=$2',[v.id,id]);return out(200,{ok:true});}}
  if(route==='feed'&&req.method==='GET'){const {at,id:cursorId}=cursorOf(url);const r=await pool.query(`WITH events AS(
   SELECT s.id,s.created_at AS at,'review'::text AS kind,jsonb_build_object('shareId',s.id,'username',a.username,'displayName',a.display_name,'isOwn',s.owner_id=$1,'overall',r.overall,'spoilers',s.spoilers,'excerpt',CASE WHEN s.spoilers THEN NULL ELSE left(s.review_text,240) END,'movieId',m.id,'title',m.title,'year',m.year,'poster',m.poster) AS data FROM social_review_shares s JOIN auth_accounts a ON a.id=s.owner_id JOIN ratings r ON r.id=s.rating_id JOIN movies m ON m.id=r.movie_id WHERE ${viewable('$1','s.owner_id')}
   UNION ALL SELECT fr.id,fr.created_at,'recommendation',jsonb_build_object('recommendationId',fr.id,'username',a.username,'displayName',a.display_name,'isOwn',fr.sender_id=$1,'spoilers',fr.spoilers,'message',CASE WHEN fr.spoilers THEN NULL ELSE fr.message END,'movieId',m.id,'title',m.title,'year',m.year,'poster',m.poster,'seen',fr.seen_at IS NOT NULL) FROM friend_recommendations fr JOIN auth_accounts a ON a.id=CASE WHEN fr.sender_id=$1 THEN fr.recipient_id ELSE fr.sender_id END JOIN movies m ON m.id=fr.movie_id WHERE (fr.sender_id=$1 OR fr.recipient_id=$1) AND fr.dismissed_at IS NULL AND ${friends('fr.sender_id','fr.recipient_id')}
   UNION ALL SELECT fc.id,fc.updated_at,'friendship',jsonb_build_object('username',a.username,'displayName',a.display_name) FROM friend_connections fc JOIN auth_accounts a ON a.id=CASE WHEN fc.requester_id=$1 THEN fc.recipient_id ELSE fc.requester_id END WHERE fc.status='accepted' AND (fc.requester_id=$1 OR fc.recipient_id=$1) AND NOT ${blocked('fc.requester_id','fc.recipient_id')}
  ) SELECT *,to_char(at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"') AS cursor_at FROM events WHERE ($2::timestamptz IS NULL OR (at,id)<($2::timestamptz,$3::uuid)) ORDER BY at DESC,id DESC LIMIT 21`,[id,at,cursorId]);const items=r.rows.slice(0,20).map(v=>({id:v.id,at:v.at,kind:v.kind,...v.data}));return out(200,{items,nextCursor:r.rows.length>20?cursor(r.rows[19]):null});}
  return out(404,{error:'Social endpoint not found.'});
 }
 return {handle,overview};
}
