export const schemaSQL = `
BEGIN;
CREATE TABLE IF NOT EXISTS profiles (id uuid PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now(), contribute boolean NOT NULL DEFAULT false);
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY, profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS movies (id text PRIMARY KEY, title text NOT NULL, year integer CHECK(year BETWEEN 1888 AND 2200), director text NOT NULL DEFAULT '', genres jsonb NOT NULL DEFAULT '[]', runtime integer, poster text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS question_versions (version integer NOT NULL, aspect_id text NOT NULL, label text NOT NULL, prompt text NOT NULL, PRIMARY KEY(version,aspect_id));
CREATE TABLE IF NOT EXISTS ratings (id uuid PRIMARY KEY, profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, movie_id text NOT NULL REFERENCES movies(id), overall numeric(2,1) NOT NULL CHECK(overall BETWEEN 0.5 AND 5 AND overall*2=trunc(overall*2)), watched_on date NOT NULL, spoilers boolean NOT NULL DEFAULT false, question_version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(id,question_version));
CREATE TABLE IF NOT EXISTS answers (rating_id uuid NOT NULL, question_version integer NOT NULL, aspect_id text NOT NULL, score smallint CHECK(score BETWEEN 0 AND 4), skip_reason text CHECK(skip_reason IN ('not_applicable','unsure')), note text NOT NULL DEFAULT '' CHECK(length(note)<=1500), PRIMARY KEY(rating_id,aspect_id), FOREIGN KEY(rating_id,question_version) REFERENCES ratings(id,question_version) ON DELETE CASCADE, FOREIGN KEY(question_version,aspect_id) REFERENCES question_versions(version,aspect_id), CHECK((score IS NULL AND skip_reason IS NOT NULL) OR (score IS NOT NULL AND skip_reason IS NULL)));
CREATE TABLE IF NOT EXISTS watchlist (profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, movie_id text NOT NULL REFERENCES movies(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(profile_id,movie_id));
CREATE INDEX IF NOT EXISTS ratings_profile_date ON ratings(profile_id,created_at DESC);
CREATE INDEX IF NOT EXISTS ratings_movie ON ratings(movie_id);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires_at);
COMMIT;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS original_title text NOT NULL DEFAULT '';
ALTER TABLE movies ADD COLUMN IF NOT EXISTS movielens_id integer;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS imdb_id text;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS tmdb_id integer;
ALTER TABLE movies ADD COLUMN IF NOT EXISTS tags jsonb NOT NULL DEFAULT '[]';
ALTER TABLE movies ADD COLUMN IF NOT EXISTS rating_count integer NOT NULL DEFAULT 0 CHECK(rating_count>=0);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS rating_mean numeric(8,6) CHECK(rating_mean BETWEEN 0.5 AND 5);
ALTER TABLE movies ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'Afterframe entry';
ALTER TABLE movies ADD COLUMN IF NOT EXISTS wallpaper text NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS movies_movielens ON movies(movielens_id) WHERE movielens_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS movies_title_lower ON movies(lower(title));
CREATE INDEX IF NOT EXISTS movies_imdb ON movies(imdb_id) WHERE imdb_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS movies_genres ON movies USING gin(genres);
CREATE TABLE IF NOT EXISTS catalogue_imports(source text PRIMARY KEY,source_version text NOT NULL,metadata jsonb NOT NULL,imported_at timestamptz NOT NULL DEFAULT now());
`;
export default schemaSQL;
